# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-10 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurl',
            name='shortener',
            field=models.CharField(default='String', max_length=20),
            preserve_default=False,
        ),
    ]
