# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-10 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170610_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurl',
            old_name='shortener',
            new_name='shortcodeurl',
        ),
    ]
