# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-10 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170610_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurl',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurl',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
