# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20170610_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurl',
            name='shortcodeurl',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
