# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20170611_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
