# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_kurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurl',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
