# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_auto_20170611_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurl',
            name='shortcodeurl',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
